name: 构建F4SE NPC信息显示插件
on:
  push:
    branches: [ main, master ]

jobs:
  build-f4se-plugin:
    runs-on: windows-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 直接通过官方安装脚本安装XMake，完全绕过已经失效的第三方action
      - name: 安装XMake构建环境
        run: irm https://xmake.io/get.ps1 | iex

      - name: 编译生成插件DLL
        run: xmake build -m release

      - name: 上传生成的插件文件
        uses: actions/upload-artifact@v4
        with:
          name: NPC信息显示插件
          path: build/windows/release/NPCInfoDisplay.dll
